version: '3'

services:
  app:
    build:
      context: ../
      dockerfile: .docker/Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - "../logs:/app/logs"
    environment:
      - MYSQL_HOST=mysql
      - MYSQL_PORT=3306
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - JWT_KEY=${JWT_KEY:-1111111111111111111111111111111111111111111111111111111111111111}
    depends_on:
      - mysql
      - redis
  mysql:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - "../schema.sql:/docker-entrypoint-initdb.d/1.sql"
      - './mysql_data:/var/lib/mysql'
  redis:
    image: redis